# Generated by Django 5.1.1 on 2024-10-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_book_author_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="authors_livro", to="myapp.author"
            ),
        ),
    ]
