# Generated by Django 5.1.1 on 2024-10-08 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_book_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="books",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_name",
                to="myapp.author",
            ),
        ),
    ]
